greenery:
  outputs:
    dbt_zkan:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: postgres
      pass: "{{ env_var('DBT_ENV_SECRET_PG_PASSWORD') }}"
      dbname: greenery
      schema: dbt_zkan

    prod:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: postgres
      pass: "{{ env_var('DBT_ENV_SECRET_PG_PASSWORD') }}"
      dbname: greenery
      schema: prod

    dbt_biw_bigquery:
      type: bigquery
      method: service-account
      project: kinetic-genre-384501
      dataset: dbt_biw
      threads: 1
      keyfile: D:\project\data-engineering-bootcamp\05-analytics-engineering\kinetic-genre-384501-9d633532a56c.json
      location: asia-southeast1

    prod_bigquery:
      type: bigquery
      method: service-account
      project: kinetic-genre-384501
      dataset: greenery
      threads: 1
      keyfile: D:\project\data-engineering-bootcamp\05-analytics-engineering\kinetic-genre-384501-9d633532a56c.json
      location: asia-southeast1

  target: dbt_biw_bigquery
